### ISSUE TITLE
Cannot find path gives "You are already at your destination"

### ISSUE THREAD

**Issue by davidtang123** [ateamwpi/HospitalKiosk#110]

**Comment by dylanrichardson** [comment]
Can you explain more?

**Comment by nmcastelino** [comment]
I think he means that rather than giving out the exception saying that the path to the location cannot be found, it prints that you are already at the required location

**Comment by dylanrichardson** [comment]
Can you give an example or a screen shot

**Comment by davidtang123** [comment]
![bad pathfinding](https://cloud.githubusercontent.com/assets/21989954/25510799/cff3b9c4-2b90-11e7-85e1-d49391610686.png)
