### ISSUE TITLE
Nodes do not specify which side of the hallway they're on

### ISSUE THREAD

**Issue by davidtang123** [ateamwpi/HospitalKiosk#111]
update existing map to show which side of hallways things are on

**Comment by dylanrichardson** [comment]
What purpose?

**Comment by davidtang123** [comment]
The pathfinding will state that the destination will be on the left/on the right, rather than just dropping them in the middle of a hallway.

**Comment by dylanrichardson** [comment]
The destination was probably in the wrong location

**Comment by davidtang123** [comment]
For example the Taiclet Family Center should be on the right side of the hallway, not the end of the hallway. I don't mean that an attribute needs to be added, but the nodes need to be repositioned

**Comment by dylanrichardson** [comment]
See #104
