### ISSUE TITLE
Placing Kiosks where appropriate

### ISSUE THREAD

**Issue by davidtang123** [ateamwpi/HospitalKiosk#113]
Also give proper names

**Comment by dylanrichardson** [comment]
There should only be one Kiosk visible to each Kiosk I think

**Comment by davidtang123** [comment]
I mean the node for the kiosk (at least on the 1st floor?) does seem to be in the right place. I'm assuming the node called First Floor is the first floor kiosk

**Comment by dylanrichardson** [comment]
It's called "Your Location"
