### ISSUE TITLE
Panning on main menu map uses right click

### ISSUE THREAD

**Issue by dylanrichardson** [ateamwpi/HospitalKiosk#82]
Should be left or right click

**Comment by davidtang123** [comment]
Since adminmapcontroller is not a super/subclass of managemapcontroller nor mapcontroller, I have no idea how to get whether a map is under adminmapcontroller or not

**Comment by dylanrichardson** [comment]
mapController instanceof ManageMapController?

What method/class are your trying to check this in?

**Comment by davidtang123** [comment]
Panning is in mapController. It's not an instanceof, since it is basically ManageMapController.mapController, not a super/subclass
