### ISSUE TITLE
Map flickers when attempting to zoom out too far

### ISSUE THREAD

**Issue by dylanrichardson** [ateamwpi/HospitalKiosk#94]

**Comment by davidtang123** [comment]
I think the origin of this problem is the same as the issue with zooming and and zooming out offsetting the map slightly.

**Comment by dylanrichardson** [comment]
Do you clamp before setting the new scale or translate?

**Comment by davidtang123** [comment]
Before. Not sure what the problem could be, unless *scale/oldscale, where scale == oldscale, does not equal 1.

**Comment by davidtang123** [comment]
Got it. It was the canvas.setPivot(scale/oldscale-1) that wasn't removed from the old version. Posting comments on Git issues is more fun than talking IRL
