### ISSUE TITLE
Navigating away from the application while a popup is present

### ISSUE THREAD

**Issue by dylanrichardson** [ateamwpi/HospitalKiosk#97]
The popup disappears but the scrim stays

**Comment by mattmcd25** [comment]
The scrim is supposed to stay thats part of the options window

**Comment by dylanrichardson** [comment]
Nah

**Comment by dylanrichardson** [comment]
It's not a big deal because the application should never loose focus

**Comment by dylanrichardson** [comment]
But if you focus on another application then come back to ours its bugged

**Comment by mattmcd25** [comment]
The popups literally don't have a scrim i dont know what you're talking about

**Comment by mattmcd25** [comment]
The only scrim is from the sidebar menu itself

**Comment by dylanrichardson** [comment]
Oh...

**Comment by dylanrichardson** [comment]
Well there are a lot of small ui bugs that result from the app loosing focus
