### ISSUE TITLE
Saving after chaining nodes

### ISSUE THREAD

**Issue by davidtang123** [ateamwpi/HospitalKiosk#99]
Saving after chain-adding nodes is funky

**Comment by dylanrichardson** [comment]
Explain

**Comment by davidtang123** [comment]
It ignores saving before adding the node rather than after adding the nodes. This leads to weird problems that I can't remember off the top of my head, but one problem is that saving will not save, and discard changes will save?

**Comment by dylanrichardson** [comment]
Find out a way to reproduce the bug

**Comment by dylanrichardson** [comment]
You should merge master into your branch. It may have already been fixed.
